OEPCIS-665: Return ProblemResponseBody when exception occurs, instead of plaintext message
openepcis/openepcis-document-converter pull request #13
Opened 2023-08-07 13:42 UTC by imrohanshah

- Add ObjectMapper in VersionTransformer to generate ProblemResponseBody's JSON representation to return.

2023-08-07 14:02 UTC, sboeckelmann requested changes
I am not convinced that this is the right place to take care of the original issue.
Code should throw Exceptions instead of swallowing them, otherwise it's not possible to setup http error status code.
Exception handling should be done in HTTP Service providers:
e.g.
openepcis-format-converter-service/converter-service-rest/src/main/java/io/openepcis/epc/converter/resource/DocumentConverterResource.java

2023-08-08 05:52 UTC, imrohanshah commented on src/main/java/io/openepcis/convert/exception/FormatConverterException.java
> +
This import is not required anymore. We will remove it asap.

2023-08-08 05:54 UTC, imrohanshah commented on src/main/java/io/openepcis/convert/VersionTransformer.java
>                                  xmlOutputStream.close();
This was a missout, we will fix it!

2023-08-08 05:54 UTC, imrohanshah commented on src/main/java/io/openepcis/convert/VersionTransformer.java
> +                                log.warn("Couldn't write or close the stream", ioe);
This exception was thrown in ExecutorService. The method returns a PipedInputStream, to which the executorService writes. If there is an exception, the caller code still receives the stream and the Exception is not getting Propagated from what we have noticed. So we decided that we could remove that throw statement.

And for this reason, we have removed thrown exception from other similar places where they were being thrown in ExecutorService and did not get propagated to the ExceptionMapper.

2023-08-08 08:36 UTC, sboeckelmann commented on src/main/java/io/openepcis/convert/VersionTransformer.java
> +                                log.warn("Couldn't write or close the stream", ioe);
Yes, okay. Refactoring it to return Multi<byte[]> would be too much effort.

2023-08-10 12:08 UTC, merged