Gs1 eg 11 support fortmat conversion with id attributes
openepcis/openepcis-document-converter pull request #25
Opened 2024-12-30 15:15 UTC by Aravinda93

@sboeckelmann 

This PR includes the logic for converting the XML <-> JSON with GS1 Egypt extensions. New SPI has been introduced to delegate the task of identifying if the document is related to GS1 Egypt if so add the specific context else for all other cases add the default GS1 context.

Also, added the similar GS1-Extensions logic to our Rest End-points and accordingly made some additional refactoring and modifications during the implementation.

Kindly request you to review the PR and approve the changes.

2024-12-30 15:34 UTC, sboeckelmann requested changes
let's plan as session for discussing how to enable SPI

2024-12-30 15:34 UTC, sboeckelmann commented on core/src/main/java/io/openepcis/converter/collector/context/ContextLogicDelegator.java
we have to add support for SPI here instead of using GS1EgyptContext directly

2024-12-30 15:34 UTC, sboeckelmann commented on core/src/main/java/io/openepcis/converter/collector/context/GS1EgyptContext.java
move GS1EgyptContext into its own SPI bundle

2024-12-30 17:21 UTC, Aravinda93 commented
Hi @sboeckelmann 

I looked at the Java SPI and its concept and, based on it made a few changes. Please let me know if this is how it should be implemented.

Surely, we will have a session for this.

2024-12-30 17:57 UTC, sboeckelmann reviewed
Let's have an SPI session

2024-12-30 17:57 UTC, sboeckelmann commented on core/src/main/java/io/openepcis/converter/collector/context/impl/GS1EgyptContextHandler.java
We will have a session ;-)

2025-01-03 15:35 UTC, sboeckelmann approved these changes

2025-01-03 15:35 UTC, merged