adding new constants and resources project as dependency and refactoring the code.
openepcis/openepcis-document-converter pull request #6
Opened 2023-02-10 21:45 UTC by Aravinda93

This project was previously using constant information from its own project. Now that we have the central openepcis-epcis-constants and openepcis-epcis-resources projects, we have added the dependency to this and used variables from there. Kindly request you to review and approve the PR.

2023-02-11 00:24 UTC, sboeckelmann requested changes

2023-02-11 00:24 UTC, sboeckelmann commented on src/main/java/io/openepcis/convert/VersionTransformer.java
>        final String fromMediaType,
also make use of new EPCISFormat

2023-02-11 00:24 UTC, sboeckelmann commented on src/main/java/io/openepcis/convert/VersionTransformer.java
>        final String toMediaType,
also make use of new EPCISFormat

2023-02-11 00:24 UTC, sboeckelmann commented on src/main/java/io/openepcis/convert/VersionTransformer.java
> +          EPCISFormat.fromString(EPCIS.XML_FORMAT).get().getMediaType(),
Use EPCISFormat - EPCIS.XML/JSON_FORMAT may be removed completely

2023-02-11 00:24 UTC, sboeckelmann commented on src/main/java/io/openepcis/convert/collector/JsonEPCISEventCollector.java
> +      jsonGenerator.writeFieldName(EPCIS.EPCIS_BODY_IN_LOWER_CASE);
This is camelCase not lowercase

2023-02-11 00:24 UTC, sboeckelmann commented on src/main/java/io/openepcis/convert/collector/JsonEPCISEventCollector.java
> +      jsonGenerator.writeString(EPCIS.DEFAULT_CONTEXT);
We might want to move the default jsonld @context from EPCIS.DEFAULT_CONTEXT to EPCISVersion.getDefaultJSONContext

2023-02-11 00:24 UTC, sboeckelmann commented on src/main/java/io/openepcis/convert/collector/XmlEPCISEventCollector.java
> +      xmlEventWriter.add(events.createEndElement(new QName(EPCIS.EVENT_LIST_IN_UPPER_CASE), null));
camelCase

2023-02-11 00:24 UTC, sboeckelmann commented on src/main/java/io/openepcis/convert/collector/XmlEPCISEventCollector.java
> +      xmlEventWriter.add(events.createEndElement(new QName(EPCIS.EPCIS_BODY_IN_UPPER_CASE), null));
CamelCase

2023-02-11 00:24 UTC, sboeckelmann commented on src/main/java/io/openepcis/convert/json/JsonToXmlConverter.java
> +        while (!jsonParser.getText().equals(EPCIS.EVENT_LIST_IN_LOWER_CASE)) {
CamelCase

2023-02-13 09:14 UTC, Aravinda93 commented
@sboeckelmann 

Thanks for the review. Based on your review I have made changes to the project. Please review and approve the PR.

2023-02-13 09:55 UTC, sboeckelmann approved these changes

2023-02-13 09:55 UTC, merged